package pl.lipinski.engineerdegree.util.error;

public enum ERRORCODES {

    EMPTY_VALUE_ERROR_CODE(500),
    PASSWORDS_DOESNT_MATCH_ERROR_CODE(501),
    USERNAME_TAKEN_ERROR_CODE(502),
    WRONG_EXPENSE_VALUE_ERROR_CODE(503),
    WRONG_BUDGET_VALUE_ERROR_CODE(504),
    BUDGET_LIST_INTERSECTION_ALREADY_EXISTS_ERROR_CODE(505),
    USER_NOT_FOUND_ERROR_CODE(506),
    BUDGET_LIST_NOT_FOUND_ERROR_CODE(507),
    INTERSECTION_NOT_FOUND_ERROR_CODE(508),
    EXPENSE_NOT_FOUND_ERROR_CODE(509),
    USER_DONT_HAVE_PERMISSIONS_ERROR_CODE(510),
    REQUESTER_NOT_FOUND_ERROR_CODE(511),
    FRIENDSHIP_INTERSECTION_ALREADY_EXISTS_ERROR_CODE(512),
    FRIENDSHIP_INTERSECTION_DOES_NOT_EXISTS_ERROR_CODE(513),
    FRIENDSHIP_WITH_SELF_NOT_ALLOWED_ERROR_CODE(514),
    CATEGORY_NOT_FOUND_ERROR_CODE(515);

    private Integer value;

    public Integer getValue()
    {
        return this.value;
    }

    ERRORCODES(Integer value)
    {
        this.value = value;
    }
}
